apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-<ip-range>
  namespace: metallb-system
spec:
  addresses:
  - <ip-range>
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: adv-<ip-range>
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-<ip-range>
---
